### ISSUE TITLE
Research Different Authentication Platforms

### ISSUE THREAD

**Issue by abramicf** [hydra-reactor/Thymer#8]
Auth-O or passport.

**Comment by emma4evr** [comment]
Auth0 seems like the easiest authentication platform to use. Their site has a lot of walk-throughs and documentation. Seems like it's very easy to choose which social media platforms to include as auth options. Most everything is managed from the Auth0 dashboard and as you manage authentication and user management options, they give you code snippets to use. There's a lot of customization options should we need them, too.

This is a great overview website/video: https://auth0.com/docs/overview

**Comment by emma4evr** [comment]
With Auth0's free plan:
7,000 free active users & unlimited logins

Passwordless & TouchID Login
Lock for Web, iOS & Android
Up to 2 social identity providers
Rules & Webtask.io subscription
